# Generated by Django 5.0.2 on 2024-02-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw', '0002_v0_0_13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='timezone',
            field=models.CharField(default='UTC', max_length=300),
        ),
    ]
