# coding: utf-8

"""
    Binance Public Spot API

    OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20081SubAccounts(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'email': 'str',
        'is_freeze': 'bool',
        'create_time': 'int',
        'is_managed_sub_account': 'bool',
        'is_asset_management_sub_account': 'bool'
    }

    attribute_map = {
        'email': 'email',
        'is_freeze': 'isFreeze',
        'create_time': 'createTime',
        'is_managed_sub_account': 'isManagedSubAccount',
        'is_asset_management_sub_account': 'isAssetManagementSubAccount'
    }

    def __init__(self, email=None, is_freeze=None, create_time=None, is_managed_sub_account=None, is_asset_management_sub_account=None):  # noqa: E501
        """InlineResponse20081SubAccounts - a model defined in Swagger"""  # noqa: E501
        self._email = None
        self._is_freeze = None
        self._create_time = None
        self._is_managed_sub_account = None
        self._is_asset_management_sub_account = None
        self.discriminator = None
        self.email = email
        self.is_freeze = is_freeze
        self.create_time = create_time
        self.is_managed_sub_account = is_managed_sub_account
        self.is_asset_management_sub_account = is_asset_management_sub_account

    @property
    def email(self):
        """Gets the email of this InlineResponse20081SubAccounts.  # noqa: E501


        :return: The email of this InlineResponse20081SubAccounts.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this InlineResponse20081SubAccounts.


        :param email: The email of this InlineResponse20081SubAccounts.  # noqa: E501
        :type: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def is_freeze(self):
        """Gets the is_freeze of this InlineResponse20081SubAccounts.  # noqa: E501


        :return: The is_freeze of this InlineResponse20081SubAccounts.  # noqa: E501
        :rtype: bool
        """
        return self._is_freeze

    @is_freeze.setter
    def is_freeze(self, is_freeze):
        """Sets the is_freeze of this InlineResponse20081SubAccounts.


        :param is_freeze: The is_freeze of this InlineResponse20081SubAccounts.  # noqa: E501
        :type: bool
        """
        if is_freeze is None:
            raise ValueError("Invalid value for `is_freeze`, must not be `None`")  # noqa: E501

        self._is_freeze = is_freeze

    @property
    def create_time(self):
        """Gets the create_time of this InlineResponse20081SubAccounts.  # noqa: E501


        :return: The create_time of this InlineResponse20081SubAccounts.  # noqa: E501
        :rtype: int
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this InlineResponse20081SubAccounts.


        :param create_time: The create_time of this InlineResponse20081SubAccounts.  # noqa: E501
        :type: int
        """
        if create_time is None:
            raise ValueError("Invalid value for `create_time`, must not be `None`")  # noqa: E501

        self._create_time = create_time

    @property
    def is_managed_sub_account(self):
        """Gets the is_managed_sub_account of this InlineResponse20081SubAccounts.  # noqa: E501


        :return: The is_managed_sub_account of this InlineResponse20081SubAccounts.  # noqa: E501
        :rtype: bool
        """
        return self._is_managed_sub_account

    @is_managed_sub_account.setter
    def is_managed_sub_account(self, is_managed_sub_account):
        """Sets the is_managed_sub_account of this InlineResponse20081SubAccounts.


        :param is_managed_sub_account: The is_managed_sub_account of this InlineResponse20081SubAccounts.  # noqa: E501
        :type: bool
        """
        if is_managed_sub_account is None:
            raise ValueError("Invalid value for `is_managed_sub_account`, must not be `None`")  # noqa: E501

        self._is_managed_sub_account = is_managed_sub_account

    @property
    def is_asset_management_sub_account(self):
        """Gets the is_asset_management_sub_account of this InlineResponse20081SubAccounts.  # noqa: E501


        :return: The is_asset_management_sub_account of this InlineResponse20081SubAccounts.  # noqa: E501
        :rtype: bool
        """
        return self._is_asset_management_sub_account

    @is_asset_management_sub_account.setter
    def is_asset_management_sub_account(self, is_asset_management_sub_account):
        """Sets the is_asset_management_sub_account of this InlineResponse20081SubAccounts.


        :param is_asset_management_sub_account: The is_asset_management_sub_account of this InlineResponse20081SubAccounts.  # noqa: E501
        :type: bool
        """
        if is_asset_management_sub_account is None:
            raise ValueError("Invalid value for `is_asset_management_sub_account`, must not be `None`")  # noqa: E501

        self._is_asset_management_sub_account = is_asset_management_sub_account

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20081SubAccounts, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20081SubAccounts):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
