# coding: utf-8

"""
    Binance Public Spot API

    OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20037(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'enabled_account': 'int',
        'max_account': 'int'
    }

    attribute_map = {
        'enabled_account': 'enabledAccount',
        'max_account': 'maxAccount'
    }

    def __init__(self, enabled_account=None, max_account=None):  # noqa: E501
        """InlineResponse20037 - a model defined in Swagger"""  # noqa: E501
        self._enabled_account = None
        self._max_account = None
        self.discriminator = None
        self.enabled_account = enabled_account
        self.max_account = max_account

    @property
    def enabled_account(self):
        """Gets the enabled_account of this InlineResponse20037.  # noqa: E501


        :return: The enabled_account of this InlineResponse20037.  # noqa: E501
        :rtype: int
        """
        return self._enabled_account

    @enabled_account.setter
    def enabled_account(self, enabled_account):
        """Sets the enabled_account of this InlineResponse20037.


        :param enabled_account: The enabled_account of this InlineResponse20037.  # noqa: E501
        :type: int
        """
        if enabled_account is None:
            raise ValueError("Invalid value for `enabled_account`, must not be `None`")  # noqa: E501

        self._enabled_account = enabled_account

    @property
    def max_account(self):
        """Gets the max_account of this InlineResponse20037.  # noqa: E501


        :return: The max_account of this InlineResponse20037.  # noqa: E501
        :rtype: int
        """
        return self._max_account

    @max_account.setter
    def max_account(self, max_account):
        """Sets the max_account of this InlineResponse20037.


        :param max_account: The max_account of this InlineResponse20037.  # noqa: E501
        :type: int
        """
        if max_account is None:
            raise ValueError("Invalid value for `max_account`, must not be `None`")  # noqa: E501

        self._max_account = max_account

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20037, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20037):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
