TIMESTAMP_TYPES='TIMESTAMP_LTZ','TIMESTAMP_NTZ','TIMESTAMP_TZ'
FLOAT_TYPES='FLOAT','DOUBLE','DOUBLE PRECISION','REAL'
STRING_TYPES='VARCHAR','TEXT','CHAR','CHARACTER','NCHAR','STRING','TEXT','NVARCHAR','NVARCHAR2','CHAR VARYING','NCHAR VARYING'