
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-27T12:48:51-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "3732ba23f787b1f7d74e656e6b4913f286f01503",
 "version": "0.4.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
