
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-29T09:57:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "37d4bf843fd27cd9531ff40f717feb45f5b61095",
 "version": "1.22.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
