from commands.booking import book_selected_slot
from commands.cancel_booking import cancel_booking
from commands.cancel_volunteer import cancel_volunteer
from commands.view_calendar import init
from commands.view_calendar import view_code_clinic_calendar
from commands.view_calendar import view_student_calendar
from commands.volunteer import volunteer_slot
