from setuptools import setup, find_packages

setup(
    name='conf-mat',
    version='1.0.2',
    author='khiat Mohammed Abderrezzak',
    author_email='khiat.abderrezzak@gmail.com',
    description='Sophisticate Open Confusion Matrix',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    packages=find_packages(),
    install_requires=[
        "tabulate>=0.9.0",
        "matplotlib>=3.8.3",
    ],
    keywords=[
        "confusion matrix",
        "confusion matrix display",
        "plot confusion matrix",
        "khiat",
        "khiat mohamed",
        "performance metrics",
        "khiat mohammed",
        "khiat abderrezzak",
        "confusion matrix visualization",
        "khiat mohamed abderrezzak",
        "khiat mohammed abderrezzak",
        "classification report",
        "khiat abderrezzak mohamed",
        "khiat abderrezzak mohammed",
        "heatmap",
        "mohamed",
        "mohammed",
        "machine learning",
        "mohamed khiat",
        "mohammed khiat",
        "deep learning",
        "mohamed abderrezzak",
        "mohammed abderrezzak",
        "data visualization",
        "mohamed abderrezzak khiat",
        "mohammed abderrezzak khiat",
        "data analysis",
        "mohamed khiat abderrezzak",
        "mohammed khiat abderrezzak",
        "beginner-friendly",
        "abderrezzak",
        "abderrezzak khiat",
        "aesthetically pleasing",
        "abderrezzak mohamed",
        "abderrezzak mohammed",
        "accuracy score calculation",
        "abderrezzak khiat mohamed",
        "abderrezzak khiat mohammed",
        "model score calculation",
        "abderrezzak mohamed khiat",
        "abderrezzak mohammed khiat",
        "confusion matrix calculation",
        "confusion matrix html display",
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
        "License :: OSI Approved :: MIT License",
    ],
)
