
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-28T17:36:10+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "41f846c66303e0d3040cae0028a8c55eb7c2359a",
 "version": "1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
