# Generated by Django 4.2.8 on 2023-12-19 14:10

import django.core.files.storage
from django.db import migrations, models
import import_export.models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasedump',
            name='file',
            field=models.FileField(help_text='The file containing the dump.', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\NigelvanKeulenGoodad\\Desktop\\goodadvice\\Projecten\\go-dev\\assets\\backups'), upload_to=import_export.models.get_import_file_path, verbose_name='File'),
        ),
    ]
