# Generated by Django 4.2 on 2023-12-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_permissiononlymodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissiononlymodel',
            options={'default_permissions': (), 'managed': False, 'permissions': (('toggle_maintenance_mode', 'Can toggle maintenance mode'), ('see_menu_item', 'Can see menu item'), ('see_info', 'Can see maintenance info')), 'verbose_name': 'Maintenance Permission Model', 'verbose_name_plural': 'Maintenance Permission Models'},
        ),
    ]
