# coding: utf-8

# flake8: noqa
"""
    PaperMC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from papermc_api.models.build_response import BuildResponse
from papermc_api.models.builds_response import BuildsResponse
from papermc_api.models.change import Change
from papermc_api.models.download import Download
from papermc_api.models.project_response import ProjectResponse
from papermc_api.models.projects_response import ProjectsResponse
from papermc_api.models.version_build import VersionBuild
from papermc_api.models.version_family_build import VersionFamilyBuild
from papermc_api.models.version_family_builds_response import VersionFamilyBuildsResponse
from papermc_api.models.version_family_response import VersionFamilyResponse
from papermc_api.models.version_response import VersionResponse
