
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-27T15:56:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "21ade5466fbb3bebef92e6baa32866c2208f8c1d",
 "version": "1.21.1.post0.dev35"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
