# coding: utf-8

"""
    Binance Public Spot API

    OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import binance_spot
from binance_spot.api.portfolio_margin_api import PortfolioMarginApi  # noqa: E501
from binance_spot.rest import ApiException


class TestPortfolioMarginApi(unittest.TestCase):
    """PortfolioMarginApi unit test stubs"""

    def setUp(self):
        self.api = PortfolioMarginApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sapi_v1_portfolio_account_get(self):
        """Test case for sapi_v1_portfolio_account_get

        Portfolio Margin Account (USER_DATA)  # noqa: E501
        """
        pass

    def test_sapi_v1_portfolio_asset_collection_post(self):
        """Test case for sapi_v1_portfolio_asset_collection_post

        Fund Collection by Asset (USER_DATA)  # noqa: E501
        """
        pass

    def test_sapi_v1_portfolio_asset_index_price_get(self):
        """Test case for sapi_v1_portfolio_asset_index_price_get

        Query Portfolio Margin Asset Index Price (MARKET_DATA)  # noqa: E501
        """
        pass

    def test_sapi_v1_portfolio_auto_collection_post(self):
        """Test case for sapi_v1_portfolio_auto_collection_post

        Fund Auto-collection (USER_DATA)  # noqa: E501
        """
        pass

    def test_sapi_v1_portfolio_bnb_transfer_post(self):
        """Test case for sapi_v1_portfolio_bnb_transfer_post

        BNB Transfer (USER_DATA)  # noqa: E501
        """
        pass

    def test_sapi_v1_portfolio_collateral_rate_get(self):
        """Test case for sapi_v1_portfolio_collateral_rate_get

        Portfolio Margin Collateral Rate (MARKET_DATA)  # noqa: E501
        """
        pass

    def test_sapi_v1_portfolio_interest_history_get(self):
        """Test case for sapi_v1_portfolio_interest_history_get

        Query Classic Portfolio Margin Negative Balance Interest History (USER_DATA)  # noqa: E501
        """
        pass

    def test_sapi_v1_portfolio_margin_asset_leverage_get(self):
        """Test case for sapi_v1_portfolio_margin_asset_leverage_get

        Get Portfolio Margin Asset Leverage (USER_DATA)  # noqa: E501
        """
        pass

    def test_sapi_v1_portfolio_pm_loan_get(self):
        """Test case for sapi_v1_portfolio_pm_loan_get

        Portfolio Margin Bankruptcy Loan Amount (USER_DATA)  # noqa: E501
        """
        pass

    def test_sapi_v1_portfolio_repay_futures_negative_balance_post(self):
        """Test case for sapi_v1_portfolio_repay_futures_negative_balance_post

        Repay futures Negative Balance (USER_DATA)  # noqa: E501
        """
        pass

    def test_sapi_v1_portfolio_repay_futures_switch_get(self):
        """Test case for sapi_v1_portfolio_repay_futures_switch_get

        Get Auto-repay-futures Status (USER_DATA)  # noqa: E501
        """
        pass

    def test_sapi_v1_portfolio_repay_futures_switch_post(self):
        """Test case for sapi_v1_portfolio_repay_futures_switch_post

        Change Auto-repay-futures Status (USER_DATA)  # noqa: E501
        """
        pass

    def test_sapi_v1_portfolio_repay_post(self):
        """Test case for sapi_v1_portfolio_repay_post

        Portfolio Margin Bankruptcy Loan Repay (USER_DATA)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
