# coding: utf-8

"""
    Binance Public Spot API

    OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20019Rows(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'isolated_symbol': 'str',
        'tx_id': 'int',
        'asset': 'str',
        'principal': 'str',
        'timestamp': 'int',
        'status': 'str'
    }

    attribute_map = {
        'isolated_symbol': 'isolatedSymbol',
        'tx_id': 'txId',
        'asset': 'asset',
        'principal': 'principal',
        'timestamp': 'timestamp',
        'status': 'status'
    }

    def __init__(self, isolated_symbol=None, tx_id=None, asset=None, principal=None, timestamp=None, status=None):  # noqa: E501
        """InlineResponse20019Rows - a model defined in Swagger"""  # noqa: E501
        self._isolated_symbol = None
        self._tx_id = None
        self._asset = None
        self._principal = None
        self._timestamp = None
        self._status = None
        self.discriminator = None
        self.isolated_symbol = isolated_symbol
        self.tx_id = tx_id
        self.asset = asset
        self.principal = principal
        self.timestamp = timestamp
        self.status = status

    @property
    def isolated_symbol(self):
        """Gets the isolated_symbol of this InlineResponse20019Rows.  # noqa: E501


        :return: The isolated_symbol of this InlineResponse20019Rows.  # noqa: E501
        :rtype: str
        """
        return self._isolated_symbol

    @isolated_symbol.setter
    def isolated_symbol(self, isolated_symbol):
        """Sets the isolated_symbol of this InlineResponse20019Rows.


        :param isolated_symbol: The isolated_symbol of this InlineResponse20019Rows.  # noqa: E501
        :type: str
        """
        if isolated_symbol is None:
            raise ValueError("Invalid value for `isolated_symbol`, must not be `None`")  # noqa: E501

        self._isolated_symbol = isolated_symbol

    @property
    def tx_id(self):
        """Gets the tx_id of this InlineResponse20019Rows.  # noqa: E501


        :return: The tx_id of this InlineResponse20019Rows.  # noqa: E501
        :rtype: int
        """
        return self._tx_id

    @tx_id.setter
    def tx_id(self, tx_id):
        """Sets the tx_id of this InlineResponse20019Rows.


        :param tx_id: The tx_id of this InlineResponse20019Rows.  # noqa: E501
        :type: int
        """
        if tx_id is None:
            raise ValueError("Invalid value for `tx_id`, must not be `None`")  # noqa: E501

        self._tx_id = tx_id

    @property
    def asset(self):
        """Gets the asset of this InlineResponse20019Rows.  # noqa: E501


        :return: The asset of this InlineResponse20019Rows.  # noqa: E501
        :rtype: str
        """
        return self._asset

    @asset.setter
    def asset(self, asset):
        """Sets the asset of this InlineResponse20019Rows.


        :param asset: The asset of this InlineResponse20019Rows.  # noqa: E501
        :type: str
        """
        if asset is None:
            raise ValueError("Invalid value for `asset`, must not be `None`")  # noqa: E501

        self._asset = asset

    @property
    def principal(self):
        """Gets the principal of this InlineResponse20019Rows.  # noqa: E501


        :return: The principal of this InlineResponse20019Rows.  # noqa: E501
        :rtype: str
        """
        return self._principal

    @principal.setter
    def principal(self, principal):
        """Sets the principal of this InlineResponse20019Rows.


        :param principal: The principal of this InlineResponse20019Rows.  # noqa: E501
        :type: str
        """
        if principal is None:
            raise ValueError("Invalid value for `principal`, must not be `None`")  # noqa: E501

        self._principal = principal

    @property
    def timestamp(self):
        """Gets the timestamp of this InlineResponse20019Rows.  # noqa: E501


        :return: The timestamp of this InlineResponse20019Rows.  # noqa: E501
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this InlineResponse20019Rows.


        :param timestamp: The timestamp of this InlineResponse20019Rows.  # noqa: E501
        :type: int
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")  # noqa: E501

        self._timestamp = timestamp

    @property
    def status(self):
        """Gets the status of this InlineResponse20019Rows.  # noqa: E501


        :return: The status of this InlineResponse20019Rows.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse20019Rows.


        :param status: The status of this InlineResponse20019Rows.  # noqa: E501
        :type: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20019Rows, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20019Rows):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
