# coding: utf-8

"""
    Binance Public Spot API

    OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse200213Rows(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'order_id': 'str',
        'collateral_coin': 'str',
        'pre_margin_call': 'str',
        'after_margin_call': 'str',
        'customize_time': 'int'
    }

    attribute_map = {
        'order_id': 'orderId',
        'collateral_coin': 'collateralCoin',
        'pre_margin_call': 'preMarginCall',
        'after_margin_call': 'afterMarginCall',
        'customize_time': 'customizeTime'
    }

    def __init__(self, order_id=None, collateral_coin=None, pre_margin_call=None, after_margin_call=None, customize_time=None):  # noqa: E501
        """InlineResponse200213Rows - a model defined in Swagger"""  # noqa: E501
        self._order_id = None
        self._collateral_coin = None
        self._pre_margin_call = None
        self._after_margin_call = None
        self._customize_time = None
        self.discriminator = None
        self.order_id = order_id
        self.collateral_coin = collateral_coin
        self.pre_margin_call = pre_margin_call
        self.after_margin_call = after_margin_call
        self.customize_time = customize_time

    @property
    def order_id(self):
        """Gets the order_id of this InlineResponse200213Rows.  # noqa: E501


        :return: The order_id of this InlineResponse200213Rows.  # noqa: E501
        :rtype: str
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id):
        """Sets the order_id of this InlineResponse200213Rows.


        :param order_id: The order_id of this InlineResponse200213Rows.  # noqa: E501
        :type: str
        """
        if order_id is None:
            raise ValueError("Invalid value for `order_id`, must not be `None`")  # noqa: E501

        self._order_id = order_id

    @property
    def collateral_coin(self):
        """Gets the collateral_coin of this InlineResponse200213Rows.  # noqa: E501


        :return: The collateral_coin of this InlineResponse200213Rows.  # noqa: E501
        :rtype: str
        """
        return self._collateral_coin

    @collateral_coin.setter
    def collateral_coin(self, collateral_coin):
        """Sets the collateral_coin of this InlineResponse200213Rows.


        :param collateral_coin: The collateral_coin of this InlineResponse200213Rows.  # noqa: E501
        :type: str
        """
        if collateral_coin is None:
            raise ValueError("Invalid value for `collateral_coin`, must not be `None`")  # noqa: E501

        self._collateral_coin = collateral_coin

    @property
    def pre_margin_call(self):
        """Gets the pre_margin_call of this InlineResponse200213Rows.  # noqa: E501


        :return: The pre_margin_call of this InlineResponse200213Rows.  # noqa: E501
        :rtype: str
        """
        return self._pre_margin_call

    @pre_margin_call.setter
    def pre_margin_call(self, pre_margin_call):
        """Sets the pre_margin_call of this InlineResponse200213Rows.


        :param pre_margin_call: The pre_margin_call of this InlineResponse200213Rows.  # noqa: E501
        :type: str
        """
        if pre_margin_call is None:
            raise ValueError("Invalid value for `pre_margin_call`, must not be `None`")  # noqa: E501

        self._pre_margin_call = pre_margin_call

    @property
    def after_margin_call(self):
        """Gets the after_margin_call of this InlineResponse200213Rows.  # noqa: E501


        :return: The after_margin_call of this InlineResponse200213Rows.  # noqa: E501
        :rtype: str
        """
        return self._after_margin_call

    @after_margin_call.setter
    def after_margin_call(self, after_margin_call):
        """Sets the after_margin_call of this InlineResponse200213Rows.


        :param after_margin_call: The after_margin_call of this InlineResponse200213Rows.  # noqa: E501
        :type: str
        """
        if after_margin_call is None:
            raise ValueError("Invalid value for `after_margin_call`, must not be `None`")  # noqa: E501

        self._after_margin_call = after_margin_call

    @property
    def customize_time(self):
        """Gets the customize_time of this InlineResponse200213Rows.  # noqa: E501


        :return: The customize_time of this InlineResponse200213Rows.  # noqa: E501
        :rtype: int
        """
        return self._customize_time

    @customize_time.setter
    def customize_time(self, customize_time):
        """Sets the customize_time of this InlineResponse200213Rows.


        :param customize_time: The customize_time of this InlineResponse200213Rows.  # noqa: E501
        :type: int
        """
        if customize_time is None:
            raise ValueError("Invalid value for `customize_time`, must not be `None`")  # noqa: E501

        self._customize_time = customize_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200213Rows, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200213Rows):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
