# coding: utf-8

"""
    Binance Public Spot API

    OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse200103(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tran_id': 'int',
        'from_email': 'str',
        'to_email': 'str',
        'asset': 'str',
        'amount': 'str',
        'from_account_type': 'str',
        'to_account_type': 'str',
        'status': 'str',
        'create_time_stamp': 'int',
        'client_tran_id': 'str'
    }

    attribute_map = {
        'tran_id': 'tranId',
        'from_email': 'fromEmail',
        'to_email': 'toEmail',
        'asset': 'asset',
        'amount': 'amount',
        'from_account_type': 'fromAccountType',
        'to_account_type': 'toAccountType',
        'status': 'status',
        'create_time_stamp': 'createTimeStamp',
        'client_tran_id': 'clientTranId'
    }

    def __init__(self, tran_id=None, from_email=None, to_email=None, asset=None, amount=None, from_account_type=None, to_account_type=None, status=None, create_time_stamp=None, client_tran_id=None):  # noqa: E501
        """InlineResponse200103 - a model defined in Swagger"""  # noqa: E501
        self._tran_id = None
        self._from_email = None
        self._to_email = None
        self._asset = None
        self._amount = None
        self._from_account_type = None
        self._to_account_type = None
        self._status = None
        self._create_time_stamp = None
        self._client_tran_id = None
        self.discriminator = None
        self.tran_id = tran_id
        self.from_email = from_email
        self.to_email = to_email
        self.asset = asset
        self.amount = amount
        self.from_account_type = from_account_type
        self.to_account_type = to_account_type
        self.status = status
        self.create_time_stamp = create_time_stamp
        self.client_tran_id = client_tran_id

    @property
    def tran_id(self):
        """Gets the tran_id of this InlineResponse200103.  # noqa: E501


        :return: The tran_id of this InlineResponse200103.  # noqa: E501
        :rtype: int
        """
        return self._tran_id

    @tran_id.setter
    def tran_id(self, tran_id):
        """Sets the tran_id of this InlineResponse200103.


        :param tran_id: The tran_id of this InlineResponse200103.  # noqa: E501
        :type: int
        """
        if tran_id is None:
            raise ValueError("Invalid value for `tran_id`, must not be `None`")  # noqa: E501

        self._tran_id = tran_id

    @property
    def from_email(self):
        """Gets the from_email of this InlineResponse200103.  # noqa: E501


        :return: The from_email of this InlineResponse200103.  # noqa: E501
        :rtype: str
        """
        return self._from_email

    @from_email.setter
    def from_email(self, from_email):
        """Sets the from_email of this InlineResponse200103.


        :param from_email: The from_email of this InlineResponse200103.  # noqa: E501
        :type: str
        """
        if from_email is None:
            raise ValueError("Invalid value for `from_email`, must not be `None`")  # noqa: E501

        self._from_email = from_email

    @property
    def to_email(self):
        """Gets the to_email of this InlineResponse200103.  # noqa: E501


        :return: The to_email of this InlineResponse200103.  # noqa: E501
        :rtype: str
        """
        return self._to_email

    @to_email.setter
    def to_email(self, to_email):
        """Sets the to_email of this InlineResponse200103.


        :param to_email: The to_email of this InlineResponse200103.  # noqa: E501
        :type: str
        """
        if to_email is None:
            raise ValueError("Invalid value for `to_email`, must not be `None`")  # noqa: E501

        self._to_email = to_email

    @property
    def asset(self):
        """Gets the asset of this InlineResponse200103.  # noqa: E501


        :return: The asset of this InlineResponse200103.  # noqa: E501
        :rtype: str
        """
        return self._asset

    @asset.setter
    def asset(self, asset):
        """Sets the asset of this InlineResponse200103.


        :param asset: The asset of this InlineResponse200103.  # noqa: E501
        :type: str
        """
        if asset is None:
            raise ValueError("Invalid value for `asset`, must not be `None`")  # noqa: E501

        self._asset = asset

    @property
    def amount(self):
        """Gets the amount of this InlineResponse200103.  # noqa: E501


        :return: The amount of this InlineResponse200103.  # noqa: E501
        :rtype: str
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this InlineResponse200103.


        :param amount: The amount of this InlineResponse200103.  # noqa: E501
        :type: str
        """
        if amount is None:
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501

        self._amount = amount

    @property
    def from_account_type(self):
        """Gets the from_account_type of this InlineResponse200103.  # noqa: E501


        :return: The from_account_type of this InlineResponse200103.  # noqa: E501
        :rtype: str
        """
        return self._from_account_type

    @from_account_type.setter
    def from_account_type(self, from_account_type):
        """Sets the from_account_type of this InlineResponse200103.


        :param from_account_type: The from_account_type of this InlineResponse200103.  # noqa: E501
        :type: str
        """
        if from_account_type is None:
            raise ValueError("Invalid value for `from_account_type`, must not be `None`")  # noqa: E501

        self._from_account_type = from_account_type

    @property
    def to_account_type(self):
        """Gets the to_account_type of this InlineResponse200103.  # noqa: E501


        :return: The to_account_type of this InlineResponse200103.  # noqa: E501
        :rtype: str
        """
        return self._to_account_type

    @to_account_type.setter
    def to_account_type(self, to_account_type):
        """Sets the to_account_type of this InlineResponse200103.


        :param to_account_type: The to_account_type of this InlineResponse200103.  # noqa: E501
        :type: str
        """
        if to_account_type is None:
            raise ValueError("Invalid value for `to_account_type`, must not be `None`")  # noqa: E501

        self._to_account_type = to_account_type

    @property
    def status(self):
        """Gets the status of this InlineResponse200103.  # noqa: E501


        :return: The status of this InlineResponse200103.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse200103.


        :param status: The status of this InlineResponse200103.  # noqa: E501
        :type: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def create_time_stamp(self):
        """Gets the create_time_stamp of this InlineResponse200103.  # noqa: E501


        :return: The create_time_stamp of this InlineResponse200103.  # noqa: E501
        :rtype: int
        """
        return self._create_time_stamp

    @create_time_stamp.setter
    def create_time_stamp(self, create_time_stamp):
        """Sets the create_time_stamp of this InlineResponse200103.


        :param create_time_stamp: The create_time_stamp of this InlineResponse200103.  # noqa: E501
        :type: int
        """
        if create_time_stamp is None:
            raise ValueError("Invalid value for `create_time_stamp`, must not be `None`")  # noqa: E501

        self._create_time_stamp = create_time_stamp

    @property
    def client_tran_id(self):
        """Gets the client_tran_id of this InlineResponse200103.  # noqa: E501


        :return: The client_tran_id of this InlineResponse200103.  # noqa: E501
        :rtype: str
        """
        return self._client_tran_id

    @client_tran_id.setter
    def client_tran_id(self, client_tran_id):
        """Sets the client_tran_id of this InlineResponse200103.


        :param client_tran_id: The client_tran_id of this InlineResponse200103.  # noqa: E501
        :type: str
        """
        if client_tran_id is None:
            raise ValueError("Invalid value for `client_tran_id`, must not be `None`")  # noqa: E501

        self._client_tran_id = client_tran_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200103, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200103):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
