# coding: utf-8

"""
    Binance Public Spot API

    OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse200235Data(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'reference_no': 'str',
        'code': 'str'
    }

    attribute_map = {
        'reference_no': 'referenceNo',
        'code': 'code'
    }

    def __init__(self, reference_no=None, code=None):  # noqa: E501
        """InlineResponse200235Data - a model defined in Swagger"""  # noqa: E501
        self._reference_no = None
        self._code = None
        self.discriminator = None
        self.reference_no = reference_no
        self.code = code

    @property
    def reference_no(self):
        """Gets the reference_no of this InlineResponse200235Data.  # noqa: E501


        :return: The reference_no of this InlineResponse200235Data.  # noqa: E501
        :rtype: str
        """
        return self._reference_no

    @reference_no.setter
    def reference_no(self, reference_no):
        """Sets the reference_no of this InlineResponse200235Data.


        :param reference_no: The reference_no of this InlineResponse200235Data.  # noqa: E501
        :type: str
        """
        if reference_no is None:
            raise ValueError("Invalid value for `reference_no`, must not be `None`")  # noqa: E501

        self._reference_no = reference_no

    @property
    def code(self):
        """Gets the code of this InlineResponse200235Data.  # noqa: E501


        :return: The code of this InlineResponse200235Data.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this InlineResponse200235Data.


        :param code: The code of this InlineResponse200235Data.  # noqa: E501
        :type: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200235Data, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200235Data):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
