# coding: utf-8

"""
    Signadot API

    API for Signadot Sandboxes  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import signadot_sdk
from signadot_sdk.api.cluster_api import ClusterApi  # noqa: E501
from signadot_sdk.rest import ApiException


class TestClusterApi(unittest.TestCase):
    """ClusterApi unit test stubs"""

    def setUp(self):
        self.api = signadot_sdk.api.cluster_api.ClusterApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_connect_cluster(self):
        """Test case for connect_cluster

        Connect Cluster  # noqa: E501
        """
        pass

    def test_create_cluster_token(self):
        """Test case for create_cluster_token

        Create Cluster Token  # noqa: E501
        """
        pass

    def test_delete_cluster_token(self):
        """Test case for delete_cluster_token

        Delete Cluster Token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
