# coding: utf-8

"""
    Signadot API

    API for Signadot Sandboxes  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import signadot_sdk_snapshot
from signadot_sdk_snapshot.models.sandbox_env_var import SandboxEnvVar  # noqa: E501
from signadot_sdk_snapshot.rest import ApiException


class TestSandboxEnvVar(unittest.TestCase):
    """SandboxEnvVar unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSandboxEnvVar(self):
        """Test SandboxEnvVar"""
        # FIXME: construct object with mandatory attributes with example values
        # model = signadot_sdk_snapshot.models.sandbox_env_var.SandboxEnvVar()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
