# Generated by Django 5.0.1 on 2024-02-12 15:17

import django.core.files.storage
import import_export.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0002_alter_databasedump_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasedump',
            name='file',
            field=models.FileField(help_text='The file containing the dump.', max_length=512, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\NigelvanKeulenGoodad\\Desktop\\goodadvice\\Projecten\\go-dev\\assets\\backups'), upload_to=import_export.models.get_import_file_path, verbose_name='File'),
        ),
    ]
