# Generated by Django 5.0.2 on 2024-02-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milea_accounts', '0005_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=128, null=True, verbose_name='email address'),
        ),
    ]
