# Autogenerated by devscripts/update-version.py

__version__ = '2024.02.28.232744'

RELEASE_GIT_HEAD = '4170b3d7120e06db3391eef39c5add18a1ddf2c3'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2024.02.28.232744dev'
