VERSION_YEAR = 2023
VERSION_MONTH = int('10')
VERSION_DAY = int('12')
VERSION_HOUR = int('18')
VERSION_MINUTE = int('35')
MAJOR_VERSION = 0
MINOR_VERSION = 9
PATCH_VERSION = 202310121835
version_date = '2023/10/12 18:35'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
