"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from dataclasses_json import Undefined, dataclass_json
from onlyauth import utils
from typing import Optional


@dataclasses.dataclass
class DeleteAppRequest:
    app_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'app_id', 'style': 'simple', 'explode': False }})
    r"""Unique identifier of the app to be deleted (APPX-XXX)"""
    client_id: str = dataclasses.field(metadata={'query_param': { 'field_name': 'client_id', 'style': 'form', 'explode': True }})
    r"""Client identifier for authentication (CLNT-XXX)"""
    



@dataclasses.dataclass
class DeleteAppApp:
    pass


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class DeleteAppResponseBody:
    r"""App deleted successfully"""
    app: Optional[DeleteAppApp] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('app'), 'exclude': lambda f: f is None }})
    



@dataclasses.dataclass
class DeleteAppResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    object: Optional[DeleteAppResponseBody] = dataclasses.field(default=None)
    r"""App deleted successfully"""
    

