
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-28T15:20:10+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d101baf74b66118c4a6bc23a55d27cc489ad1f2",
 "version": "2.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
