# coding: utf-8

"""
    SmartHome

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mpsmarthome.models.auth_request import AuthRequest  # noqa: E501

class TestAuthRequest(unittest.TestCase):
    """AuthRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthRequest:
        """Test AuthRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthRequest`
        """
        model = AuthRequest()  # noqa: E501
        if include_optional:
            return AuthRequest(
                email_address = '',
                password = ''
            )
        else:
            return AuthRequest(
        )
        """

    def testAuthRequest(self):
        """Test AuthRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
