_A='TEXT'
PG_VARIANT_TYPE=_A
PG_VARIANT_COMPATIBLE_TYPES='JSONB','FLOAT','BIGINT','BOOLEAN',_A
PG_VARIANT_TYPES_AND_ARRAYS=PG_VARIANT_COMPATIBLE_TYPES+('FLOAT[]','INTEGER[]','BOOLEAN[]','TEXT[]')
NUMERIC_TYPES='DECIMAL','INTEGER'
BASIC_TYPES=(_A,)+NUMERIC_TYPES
DEFAULT_DATABASE='test'
DEFAULT_SCHEMA='public'