# coding: utf-8

"""
    Binance Public Spot API

    OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20079ExchangeRates(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'usdc': 'str',
        'tusd': 'str',
        'usdp': 'str'
    }

    attribute_map = {
        'usdc': 'USDC',
        'tusd': 'TUSD',
        'usdp': 'USDP'
    }

    def __init__(self, usdc=None, tusd=None, usdp=None):  # noqa: E501
        """InlineResponse20079ExchangeRates - a model defined in Swagger"""  # noqa: E501
        self._usdc = None
        self._tusd = None
        self._usdp = None
        self.discriminator = None
        self.usdc = usdc
        self.tusd = tusd
        self.usdp = usdp

    @property
    def usdc(self):
        """Gets the usdc of this InlineResponse20079ExchangeRates.  # noqa: E501


        :return: The usdc of this InlineResponse20079ExchangeRates.  # noqa: E501
        :rtype: str
        """
        return self._usdc

    @usdc.setter
    def usdc(self, usdc):
        """Sets the usdc of this InlineResponse20079ExchangeRates.


        :param usdc: The usdc of this InlineResponse20079ExchangeRates.  # noqa: E501
        :type: str
        """
        if usdc is None:
            raise ValueError("Invalid value for `usdc`, must not be `None`")  # noqa: E501

        self._usdc = usdc

    @property
    def tusd(self):
        """Gets the tusd of this InlineResponse20079ExchangeRates.  # noqa: E501


        :return: The tusd of this InlineResponse20079ExchangeRates.  # noqa: E501
        :rtype: str
        """
        return self._tusd

    @tusd.setter
    def tusd(self, tusd):
        """Sets the tusd of this InlineResponse20079ExchangeRates.


        :param tusd: The tusd of this InlineResponse20079ExchangeRates.  # noqa: E501
        :type: str
        """
        if tusd is None:
            raise ValueError("Invalid value for `tusd`, must not be `None`")  # noqa: E501

        self._tusd = tusd

    @property
    def usdp(self):
        """Gets the usdp of this InlineResponse20079ExchangeRates.  # noqa: E501


        :return: The usdp of this InlineResponse20079ExchangeRates.  # noqa: E501
        :rtype: str
        """
        return self._usdp

    @usdp.setter
    def usdp(self, usdp):
        """Sets the usdp of this InlineResponse20079ExchangeRates.


        :param usdp: The usdp of this InlineResponse20079ExchangeRates.  # noqa: E501
        :type: str
        """
        if usdp is None:
            raise ValueError("Invalid value for `usdp`, must not be `None`")  # noqa: E501

        self._usdp = usdp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20079ExchangeRates, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20079ExchangeRates):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
