# coding: utf-8

"""
    Binance Public Spot API

    OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import binance_spot
from binance_spot.api.futures_algo_api import FuturesAlgoApi  # noqa: E501
from binance_spot.rest import ApiException


class TestFuturesAlgoApi(unittest.TestCase):
    """FuturesAlgoApi unit test stubs"""

    def setUp(self):
        self.api = FuturesAlgoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sapi_v1_algo_futures_historical_orders_get(self):
        """Test case for sapi_v1_algo_futures_historical_orders_get

        Query Historical Algo Orders (USER_DATA)  # noqa: E501
        """
        pass

    def test_sapi_v1_algo_futures_new_order_twap_post(self):
        """Test case for sapi_v1_algo_futures_new_order_twap_post

        Time-Weighted Average Price(Twap) New Order (TRADE)  # noqa: E501
        """
        pass

    def test_sapi_v1_algo_futures_new_order_vp_post(self):
        """Test case for sapi_v1_algo_futures_new_order_vp_post

        Volume Participation(VP) New Order (TRADE)  # noqa: E501
        """
        pass

    def test_sapi_v1_algo_futures_open_orders_get(self):
        """Test case for sapi_v1_algo_futures_open_orders_get

        Query Current Algo Open Orders (USER_DATA)  # noqa: E501
        """
        pass

    def test_sapi_v1_algo_futures_order_delete(self):
        """Test case for sapi_v1_algo_futures_order_delete

        Cancel Algo Order(TRADE)  # noqa: E501
        """
        pass

    def test_sapi_v1_algo_futures_sub_orders_get(self):
        """Test case for sapi_v1_algo_futures_sub_orders_get

        Query Sub Orders (USER_DATA)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
