# automatically generated by the FlatBuffers compiler, do not modify

# namespace: routes

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class empty_payload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = empty_payload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsempty_payload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # empty_payload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def empty_payloadStart(builder):
    builder.StartObject(0)

def Start(builder):
    empty_payloadStart(builder)

def empty_payloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return empty_payloadEnd(builder)
