#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2401-87-g6bb015a8"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2401
#define NETGEN_VERSION_TWEAK 87
#define NETGEN_VERSION_HASH "g6bb015a8"
#endif // NETGEN_VERSION_HPP_INCLUDED
