# coding: utf-8

"""
    Signadot API

    API for Signadot Sandboxes  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import signadot_sdk
from signadot_sdk.models.fork_endpoint import ForkEndpoint  # noqa: E501
from signadot_sdk.rest import ApiException


class TestForkEndpoint(unittest.TestCase):
    """ForkEndpoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testForkEndpoint(self):
        """Test ForkEndpoint"""
        # FIXME: construct object with mandatory attributes with example values
        # model = signadot_sdk.models.fork_endpoint.ForkEndpoint()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
