# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.24
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from perian.models.create_organization_success import CreateOrganizationSuccess

class TestCreateOrganizationSuccess(unittest.TestCase):
    """CreateOrganizationSuccess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOrganizationSuccess:
        """Test CreateOrganizationSuccess
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOrganizationSuccess`
        """
        model = CreateOrganizationSuccess()
        if include_optional:
            return CreateOrganizationSuccess(
                status = 'Success',
                message = 'Operation was successful',
                detail = 'Organization created successfully',
                status_code = 56,
                organization = perian.models.organization.Organization(
                    name = '', )
            )
        else:
            return CreateOrganizationSuccess(
                organization = perian.models.organization.Organization(
                    name = '', ),
        )
        """

    def testCreateOrganizationSuccess(self):
        """Test CreateOrganizationSuccess"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
