# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.24
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from perian.api.service_account_api import ServiceAccountApi


class TestServiceAccountApi(unittest.TestCase):
    """ServiceAccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServiceAccountApi()

    def tearDown(self) -> None:
        pass

    def test_create_service_account_service_account_post(self) -> None:
        """Test case for create_service_account_service_account_post

        Create Service Account
        """
        pass


if __name__ == '__main__':
    unittest.main()
