# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.24
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from perian.models.response_get_job_job_get import ResponseGetJobJobGet

class TestResponseGetJobJobGet(unittest.TestCase):
    """ResponseGetJobJobGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseGetJobJobGet:
        """Test ResponseGetJobJobGet
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseGetJobJobGet`
        """
        model = ResponseGetJobJobGet()
        if include_optional:
            return ResponseGetJobJobGet(
                status = None,
                message = None,
                detail = None,
                status_code = None,
                jobs = None
            )
        else:
            return ResponseGetJobJobGet(
                jobs = None,
        )
        """

    def testResponseGetJobJobGet(self):
        """Test ResponseGetJobJobGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
