
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-29T09:22:00+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a45a4f7a998c621c13284202d0fdd5c3658f78a7",
 "version": "1.28.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
